### PR TITLE
version 1.4

### PR DESCRIPTION
**Pull request by Artur91425**
Be sure to remove old SavedVariables!

Added localization support
Added ruRU localization
Added 'debug' command
Added error messages if invalid variables were entered
New style for print, error, debug messages
Small optimization and cleaning of the code

### CODE REVIEW

**Comment by Artur91425** [comment]
sorry, I did not notice. In my PR there is no last commit 4dad9c4c96e42b92dff59233990d0b6fe9465872

**Comment by Artur91425** [comment]
I can do it again, adding changes from your commit

**Comment by Artur91425** [comment]
omg... sorry again... everything is fine. I rechecked, your commit is present in my PR

**Comment by Road-block** [comment]
I accepted merge but won't do a release until I do a pass myself, also waiting for some guy to provide Chinese version to pickup at least the spell names.  
Thanks for your work 😄

**Comment by Artur91425** [comment]
i can provide spell names for all locales

**Pull request merged**
